<a href="https://colab.research.google.com/github/Karsang-Chhombay-sherpa/AI-ML/blob/main/ANOVA_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import seaborn as sns
from scipy import stats
from scipy.stats import chi2_contingency
import pandas as pd

In [3]:
df=sns.load_dataset('titanic')

In [4]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [7]:
contingency_table=pd.crosstab(df['sex'],df['survived'])

In [8]:
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [9]:
chi2,p_value,dof,expected=chi2_contingency(contingency_table)

In [11]:
expected

array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]])

In [12]:
chi2

np.float64(260.71702016732104)

In [13]:
alpha=0.05

In [14]:
if p_value<alpha:
  print("reject")
else:
  print("accept")

reject

In [15]:
import seaborn as sns
import pandas as pd
from scipy.stats import f_oneway

In [16]:
df=sns.load_dataset("titanic")

In [17]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [33]:
df=df[['age','pclass']].dropna()

In [34]:
df['pclass'].unique()

array([3, 1, 2])

In [35]:
class_1=df[df['pclass']==1]['age']
class_2=df[df['pclass']==2]['age']
class_3=df[df['pclass']==3]['age']

In [36]:
class_1

1      38.0
3      35.0
6      54.0
11     58.0
23     28.0
       ...
871    47.0
872    33.0
879    56.0
887    19.0
889    26.0
Name: age, Length: 186, dtype: float64

In [37]:
f_stats,p_value=f_oneway(class_1,class_2,class_3)

In [39]:
float(f_stats)

57.44348434067624

In [41]:
float(p_value)

7.487984171959213e-24

In [42]:
alpha=0.05

In [44]:
if p_value<alpha:
  print("reject")
else:
  print("accept")

reject